[project]
name = "venv-apex-digital"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.5"
dependencies = [
    "fireducks>=1.4.1",
    "scikit-learn>=1.7.2",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
]
